[package]
name = "sw-ibm1130-target"
version = "0.1.0"
edition = "2024"
description = "IBM 1130 Target description: ABI, calling convention, register classes"
license = "MIT"

[dependencies]
sw-isa-core = { path = "/Users/mike/github/sw-langtools/sw-isa-core" }
sw-target-core = { path = "/Users/mike/github/sw-langtools/sw-target-core" }
sw-ibm1130-isa = { path = "../sw-ibm1130-isa" }
